---
# Task 1 - Installation of main EFM 1.7.x required components
# TODO 1: change paths for each task from "full/path/to"  to the location in your personal Ansible workstation
# TODO 2: change host target from "hostname" to the host aliases you wish to run this script on
- hosts: hostname
  become: true
  tasks:
          - name: Installation of main EFM 1.7.x required components
            include_tasks: full/path/to/roles/efm17x/tasks/main.yml

# Task 2a - Installation of DGLux5 EFM 1.7.x component for generating interactive dashboards           

- hosts: hostname
  become: true
  tasks:
          - name: Installation of DGLux5 EFM 1.7.x component for generating interactive dashboards
            include_tasks: full/path/to/roles/efm17x/tasks/dglux.yml

# Task 3 - Installation and configuration of Mosquitto MQTT broker

- hosts: hostname
  become: true
  tasks:
          - name: Installation of Mosquitto MQTT broker
            include_tasks: full/path/to/roles/efm17x/tasks/mosquitto.yml
            
# Task 4  - DB Installation an configuration
# TODO

# Task 5 (optional) - Demo Dashboard Installation
#- hosts: test
#  become: true
#  tasks:
#          - name: Demo Chart Ferrox Dashboard installation
#            include_tasks: /full/path/to/demo-dash.yml  
